# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rubocop-packaging/all/rubocop-packaging.rbi
#
# rubocop-packaging-0.5.1

module RuboCop
end
module RuboCop::Packaging
end
module RuboCop::Packaging::Inject
  def self.defaults!; end
end
module RuboCop::Packaging::LibHelperModule
  def inspected_file_falls_in_lib?; end
  def inspected_file_is_gemspec?; end
  def inspected_file_is_not_in_lib_or_gemspec?; end
  def root_dir; end
  def target_falls_in_lib?(str); end
  def target_falls_in_lib_using_file?(str); end
end
module RuboCop::Cop
end
module RuboCop::Cop::Packaging
end
class RuboCop::Cop::Packaging::BundlerSetupInTests < RuboCop::Cop::Base
  def autocorrect(corrector, node); end
  def bundler_setup?(param0 = nil); end
  def bundler_setup_in_test_dir?(str); end
  def falls_in_test_dir?; end
  def on_new_investigation; end
  def on_send(node); end
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Cop::RangeHelp
  include RuboCop::Packaging::LibHelperModule
end
class RuboCop::Cop::Packaging::GemspecGit < RuboCop::Cop::Base
  def on_new_investigation; end
  def starts_with_git?(str); end
  def xstr(param0); end
end
class RuboCop::Cop::Packaging::RequireHardcodingLib < RuboCop::Cop::Base
  def falls_in_lib?(str); end
  def falls_in_lib_using_file?(str); end
  def falls_in_lib_with_file_dirname_plus_str?(str); end
  def good_require_call; end
  def on_new_investigation; end
  def on_send(node); end
  def require?(param0 = nil); end
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Packaging::LibHelperModule
end
class RuboCop::Cop::Packaging::RequireRelativeHardcodingLib < RuboCop::Cop::Base
  def falls_in_lib?(str); end
  def good_require_call; end
  def on_new_investigation; end
  def on_send(node); end
  def require_relative(param0 = nil); end
  extend RuboCop::Cop::AutoCorrector
  include RuboCop::Packaging::LibHelperModule
end
