require:
  - rubocop-sorbet
  - rubocop-minitest

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ffprober.gemspec'

Style/Documentation:
  Enabled: false

# This will mess with Sorbet signatures
Style/AccessorGrouping:
  Enabled: false

Sorbet/StrictSigil:
  Exclude:
    - 'lib/ffprober.rb'
    - 'lib/ffprober/dynamic_initializer.rb'
    - 'lib/ffprober/parsers/json.rb'
    - 'lib/ffprober/parsers/url.rb'
    - 'lib/ffprober/wrapper.rb'
    - 'test/*'
