require: rubocop-sorbet

AllCops:
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ffprober.gemspec'

Style/Documentation:
  Enabled: false

# This will mess with Sorbet signatures
Style/AccessorGrouping:
  Enabled: false
